apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::220719767845:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-c4HhDs6D82UP
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  # mapUsers: |
  #   - groups:
  #     - krishna
  #     userarn: arn:aws:iam::220719767845:user/krishna
  #     username: krishna  
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-03T06:55:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1147"
  uid: 8d54af18-c6b6-4d19-9908-c39fbf4732ab