apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::220719767845:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-Q0Cn3dyoR8Ek
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - krishna
      userarn: arn:aws:iam::220719767845:user/krishna
      username: krishna    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-04T03:11:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1228"
  uid: 2ed23167-9ec3-4f88-b971-c32ad8a2bee0

