apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::220719767845:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-EXGOXQmPJ7fI
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-service-account
  namespace: roboshop
  

